allow_dye_sheep: true
bow_buff: 1.000000
ender_pearl_teleportation_throttled: true
ender_pearl_teleportation: true
fix_teleport_glitch: true
villager_trades: false
anvil: true
ender_chest: false
ender_chests_placeable: true
unlimitedcauldron: true
quartz_gravel_percentage: 0.0
portalcreate: true
enderdragon: true
joinquitkick: true
deathannounce: true
deathlog: false
deathpersonal: false
deathred: false
ender_backpacks: false
endergrief: true
wither_insta_break: false
wither_explosions: false
wither: true
extra_ghast_spawn_rate: 0.0
extra_wither_skele_spawn_rate: 0.0
portal_extra_ghast_spawn_rate: 0.0
portal_extra_wither_skele_spawn_rate: 0.0
portal_pig_spawn_multiplier: 0.0
wither_skull_drop_rate: 0.0
ench_gold_app_edible: false
ench_book_craftable: false
cobble_from_lava: true
cobble_from_lava_scan_radius: 0
scale_protection_enchant: true
player_max_health: 20
fix_rail_dup_bug: true
tag_on_join: true
drop_newbie_kit: false
drop_newbie_book: false
disallow_record_playing: false
allow_water_in_nether: true
indestructible_end_portals: true
drop_ores_as_ore: false
obsidian_generator: false
nerf_strength: true
strength_multiplier: 3
buff_health_pots: true
disable_chorus_fruit: true
disable_elytra: true
disable_bed_nether_end: true
projectile_slow_chance: 30
projectile_slow_ticks: 100
ignore_experience: false
disable_experience: true
xp_per_bottle: 10
find_end_portals: true
prevent_opening_container_carts: true
prevent_vehicle_inventory_open: true
disable_hopper_out_transfers: false
horse_speed: 0.170000
prevent_self_boat_break: true
prevent_land_boats: true
prevent_ender_pearl_save: true
fix_vehicle_logout_bug: true
fix_minecart_reenter_bug: true
ender_pearl_gravity: 0.060000
saturation_multiplier: 0.0
hunger_slowdown: 0.0
prevent_tree_wraparound: true
equipping_banners: true
changing_spawners_with_eggs: true
prevent_long_signs: true
prevent_long_signs_limit: 100
prevent_long_signs_allornothing: true
prevent_long_signs_cancelevent: false
prevent_long_signs_in_chunks: true
